version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.16.0

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/workspace/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install dependencies
          command: npm install
      - save_npm
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Run build
          command: npm run build
  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Run test
          command: npm run test

workflows:
  test_and_deploy:
    jobs:
      - setup:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
            - setup
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
