version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.16.0

commands:
  # ここにコマンドを定義する
  restore_npm: # コマンド の名前（任意）
    steps: # 再利用したステップをここに記載
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}

  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/workspace/node_modules
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm # 使いたいコマンドを指定するとそのコマンドで定義したステップが展開される
      - run:
          name: Install dependencies
          command: npm install
      - save_npm
  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Run test
          command: npm run test